'use strict';import{AssertionError,AttributeError,BaseException,DeprecationWarning,Exception,IndexError,IterableError,KeyError,NotImplementedError,RuntimeWarning,StopIteration,UserWarning,ValueError,Warning,__JsIterator__,__PyIterator__,__Terminal__,__add__,__and__,__call__,__class__,__envir__,__eq__,__floordiv__,__ge__,__get__,__getcm__,__getitem__,__getslice__,__getsm__,__gt__,__i__,__iadd__,__iand__,__idiv__,__ijsmod__,__ilshift__,__imatmul__,__imod__,__imul__,__in__,__init__,__ior__,__ipow__,
__irshift__,__isub__,__ixor__,__jsUsePyNext__,__jsmod__,__k__,__kwargtrans__,__le__,__lshift__,__lt__,__matmul__,__mergefields__,__mergekwargtrans__,__mod__,__mul__,__ne__,__neg__,__nest__,__or__,__pow__,__pragma__,__proxy__,__pyUseJsNext__,__rshift__,__setitem__,__setproperty__,__setslice__,__sort__,__specialattrib__,__sub__,__super__,__t__,__terminal__,__truediv__,__withblock__,__xor__,abs,all,any,assert,bool,bytearray,bytes,callable,chr,copy,deepcopy,delattr,dict,dir,divmod,enumerate,filter,float,
getattr,hasattr,input,int,isinstance,issubclass,len,list,map,max,min,object,ord,pow,print,property,py_TypeError,py_iter,py_metatype,py_next,py_reversed,py_typeof,range,repr,round,set,setattr,sorted,str,sum,tuple,zip}from"./org.transcrypt.__runtime__.js";var __name__="__main__";export var c=0;export var Slider=__class__("Slider",[object],{__module__:__name__,get __init__(){return __get__(this,function(self,py_selector,data){if(typeof data=="undefined"||data!=null&&data.hasOwnProperty("__kwargtrans__"))var data=
dict({"velocity":1,"direction":"left","orientation":"horizontal","width":"auto","height":"auto"});if(py_typeof(py_selector)==str)self.document=document.querySelectorAll(py_selector);else if(NodeList.prototype.isPrototypeOf(py_selector))self.document=py_selector;else if(Node.prototype.isPrototypeOf(py_selector))self.document=[py_selector];else self.document=py_selector;self.maxdistance=0;self.second_delay=0;self.direction=__in__("direction",data)?data["direction"]:"left";self.orientation=__in__("orientation",
data)?data["orientation"]:"horizontal";self.height=py_typeof(data["height"])==str?data["height"]:"{}px".format(data["height"]);self.width=py_typeof(data["width"])==str?data["width"]:"{}px".format(data["width"]);self.velocity=__in__("velocity",data)?data["velocity"]:1;self.mode="prod";self.sliders=dict({})})},get loop(){return __get__(this,function(self,slider){var fn=function(slider){var node=self.document[slider].querySelector(".slowslider-content");var doc=self.sliders[slider];if(!doc.paused)if(self.direction==
"left"){node.scrollLeft++;self.sliders[slider]["scrollleft"]=node.scrollLeft;if(node.scrollLeft>=self.sliders[slider]["maxdistance"]){node.scrollLeft=0;self.sliders[slider]["scrollleft"]=node.scrollLeft}}else if(self.direction=="right"){node.scrollLeft--;self.sliders[slider]["scrollleft"]=node.scrollLeft;var constante=35;if(node.scrollLeft<=node.maxscroll*(self.sliders[slider]["maxdistance"]-node.offsetWidth)/node.scrollWidth+constante)node.scrollLeft=node.scrollWidth}self.sliders[slider]["control"]=
false};if(!self.sliders[slider]["control"]){self.sliders[slider]["control"]=true;setTimeout(function __lambda__(){return fn(slider)},self.sliders[slider]["second_delay"])}})},get dragstart(){return __get__(this,function(self,evt){for(var [k,elem]of enumerate(self.document)){var found=true;var __break1__=false;for(var slider of evt.path)if(elem==slider){__break1__=true;break}if(!__break1__)var found=false;if(found)break}slider.x=evt.clientX;slider.y=evt.clientY;slider.paused=true})},get drag(){return __get__(this,
function(self,evt){for(var [k,elem]of enumerate(self.document)){var found=true;var __break1__=false;for(var slider of evt.path)if(elem==slider){__break1__=true;break}if(!__break1__)var found=false;if(found)break}var dx=evt.clientX-slider.x;var dy=evt.clientY-slider.y;slider.x=evt.clientX;slider.y=evt.clientY;slider.paused=true;if(self.orientation=="horizontal"){slider.querySelector(".slowslider-content").scrollLeft+=dx;self.sliders[k]["scrollleft"]=slider.querySelector(".slowslider-content").scrollLeft}else if(self.orientation==
"vertical")slider.querySelector(".slowslider-content").scrollTop+=dy})},get dragend(){return __get__(this,function(self,evt){for(var [k,elem]of enumerate(self.document)){var found=true;var __break1__=false;for(var slider of evt.path)if(elem==slider){__break1__=true;break}if(!__break1__)var found=false;if(found)break}slider.querySelector(".slowslider-content").scrollLeft=self.sliders[k]["scrollleft"];slider.paused=false})},get mouseover(){return __get__(this,function(self,evt){for(var [k,elem]of enumerate(self.document)){var found=
true;var __break1__=false;for(var slider of evt.path)if(elem==slider){__break1__=true;break}if(!__break1__)var found=false;if(found)break}self.sliders[k]["second_delay"]=50})},get mouseout(){return __get__(this,function(self,evt){for(var [k,elem]of enumerate(self.document)){var found=true;var __break1__=false;for(var slider of evt.path)if(elem==slider){__break1__=true;break}if(!__break1__)var found=false;if(found)break}self.sliders[k]["second_delay"]=0})},get recursive(){return __get__(this,function(self,
node,fn){for(var node of node.children){fn(node);self.recursive(node,fn)}})},get reload(){return __get__(this,function(self){for(var [k,doc]of enumerate(self.document)){var node=doc.querySelector("[data-height]");if(node!=null){self.height=node.attributes["data-height"].value;if(__in__("data-velocity",node.attributes))self.velocity=int(node.attributes["data-velocity"].value.py_replace("px",""));if(__in__("data-width",node.attributes))self.width=node.attributes["data-width"].value;if(__in__("data-direction",
node.attributes))self.direction=node.attributes["data-direction"].value;if(__in__("data-orientation",node.attributes))self.orientation=node.attributes["data-orientation"].value}var clones=[];doc.maxdistance=0;var children=doc.querySelector(".slowslider-content").children;for(var node of children)if(__in__("data-clone",node.attributes))node.remove();var children=doc.querySelector(".slowslider-content").children;for(var node of children){clones.append(node.cloneNode(true));self.sliders[k]["maxdistance"]+=
node.offsetWidth}for(var node of clones){node.setAttribute("data-clone",true);doc.querySelector(".slowslider-content").appendChild(node)}}})},get run(){return __get__(this,function(self){for(var [k,doc]of enumerate(self.document)){doc.setAttribute("draggable",true);doc.paused=false;if(__in__("slider",dir(doc))){clearInterval(doc.sider.mainloop);delete doc.slider}doc.addEventListener("mouseover",self.mouseover);doc.addEventListener("mouseout",self.mouseout);self.sliders[k]=dict({});self.sliders[k]["scrollleft"]=
0;self.sliders[k]["scrolltop"]=0;self.sliders[k]["second_delay"]=0;self.sliders[k]["control"]=false;self.sliders[k]["maxdistance"]=0;doc.slider=self;var node=doc.querySelector(".slowslider-content");if(self.mode=="prod")node.style.overflow="hidden";else if(self.mode=="edit")node.style.overflow="scroll";if(self.orientation=="horizontal")node.style.flexDirection="row";else if(self.orientation=="vertical"){node.style.flexDirection="column";node.style.height=height}node.style.height=self.height;node.style.width=
self.width;node.style.display="flex";node.style.flexDirection="row";self.reload();if(self.direction=="right"){node.scrollLeft=node.scrollWidth;self.sliders[k]["maxdistance"]+=node.offsetWidth}self.maxscroll=node.scrollLeft;if(self.mode=="prod")doc.mainloop=setInterval(function __lambda__(){return self.loop(k)},self.velocity)}})}});

//# sourceMappingURL=slider_deslizante.map